production:
  hosts:
    omero:
      ansible_host: "{{ vault_ansible_host }}"
      ansible_user: local
      deployment_repo: "https://github.com/NL-BioImaging/omero-deployment-kit.git"
      deployment_branch: "maastricht-production"
      server_name: "omero.maastrichtuniversity.nl"
      omero_uid: 5998
      postgres_init_uid: 0
      postgres_init_gid: 0
      omero_web_uid: 999
      omero_web_gid: 999