test:
  hosts:
    omero:
      ansible_host: 192.168.124.11
      ansible_user: local
      deployment_repo: https://github.com/NL-BioImaging/omero-deployment-kit.git
      deployment_branch: "maastricht-test"
      server_name: "localhost"
      omero_uid: 5998
      postgres_init_uid: 0
      postgres_init_gid: 0
      omero_web_uid: 999
      omero_web_gid: 999